#apiVersion: v1
#kind: Service              # 1
#metadata:
#  name: coit-frontend-lb
#spec: 
#  type: LoadBalancer
#  ports:
#  - port: 80               # 3
#    protocol: TCP          # 4
#    targetPort: 80         # 5
#  selector:                # 6
#    app: coit-frontend       # 7
#
apiVersion: v1
kind: Service
metadata:
  name: coit-frontend 
spec: 
  type: NodePort
  selector:
    app: coit-frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
    
